### ISSUE TITLE
Unable to build Example project in Xcode 9

### ISSUE THREAD

**Issue by jurvis** [exyte/Macaw#143]
I'm trying to run the example project from the instructions provided in the README: https://github.com/exyte/Macaw#building-from-sources but am unfortunately running into the following build error in Xcode 9:

![image](https://user-images.githubusercontent.com/5944973/28824414-5ff62e5e-76f4-11e7-8a99-16e3b370fe38.png)

I also get the same build error when adding the Pod to an existing project.

does anyone know how to fix this or can tell me what I'm doing wrong?

**Comment by wir349** [comment]
The fix is really simple, I'm just new with Cocoapods so I don't know how to push an update yet. 

Macaw is using the dependency SWXMLHash 3.1, which has this bug. The fix is to use the latest version of the SWXMLHash (4.0 or similar) which has the fix, after that there's two places where the code needs to be updated (changing optionals to non-optionals) and the library should work. I've tried compiling it and it seems okay, not sure if there are any side effects of upgrading the library.

**Comment by jurvis** [comment]
ah! no idea why but I did what you said and changed the version of SWXMLHash to `4.1.1` and it works 100% fine now without any change needed to the code at all.

thanks for taking the time!

**Comment by braveS** [comment]
@jurvis could you please tell, how did you change the SWXMLHash version?

**Comment by jurvis** [comment]
@braveS go into `Macaw.podspec` and change the line `s.dependency 'SWXMLHash', '~> 3.0.0'` to `s.dependency 'SWXMLHash', '~> 4.1.0'`
