### ISSUE TITLE
opacity works but fill doesn't work

### ISSUE THREAD

**Issue by orcunorcun** [exyte/Macaw#606]
Hello everyone,

I am trying to fill color some part of svg file. opacity works well but fill doesn't work. I get error "Value of type 'Node' has no member 'fill'"

Here my code:

   

>     let testGroup = try! SVGParser.parse(path: "place")  as! Group
>         for shape in testGroup.contents {
>             shape.onTap { _ in
>                 shape.fill = Color.rgb(r: Int(204.0), g: Int(0.0), b: Int(51.0))  // error here
>                 shape.opacity = 1.0
>             }
>         }
> 

Thank you for your answers.

**Comment by ystrot** [comment]
Hi Orçun,

That's because `testGroup.contents` return you list of `Node`, not `Shape`. And `Node` is a base class, it can be image or group which don't have fill.

Check out this code sample to go through all nodes in SVG and change fill of shapes: https://github.com/exyte/Macaw/issues/603#issuecomment-501655160
