### ISSUE TITLE
Make Macaw Catalyst enabled

### ISSUE THREAD

**Issue by khatchik** [exyte/Macaw#610]
Hi!,

We've been using your library to render SVGs and we are preparing our iOS App to be delivered in Mac OSX. As part of that work we had to fork the library and do a minor adjustment to be able to make it "Catalyst" enabled. 

We had to go to the project.pbxproj and change:
SDKROOT = iphoneos;
SWIFT_VERSION = 5.0;

Is there a chance we can get those fixes in the next release so we can release our Mac App from the official repo?

Thanks in advance!

**Comment by khatchik** [comment]
Any news here?

**Comment by amarunko** [comment]
Hi, @khatchik, Macaw already included swift version = 5 config. In which section of pbxproj did you enable this setting? Also, for mac os users - Macaw shouldn't have base SDK - iOS, sorry. But, if you are using cocoapods as a dependency manager, you can set up project settings from the pod file. 

for example:
```
post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SDKROOT'] = 'iphoneos'
    end
  end
end
```

**Comment by simonboots** [comment]
I just did another round of tests (with Xcode 11 beta 5 and in Macaw's `master` branch), and the only changes needed to make Macaw Catalyst-ready is to change `SUPPORTED_PLATFORMS` to include `macosx` in the `Macaw` target:

`- SUPPORTED_PLATFORMS = "iphonesimulator iphoneos";`
`+ SUPPORTED_PLATFORMS = "iphonesimulator iphoneos macosx";`

Alternatively, `SUPPORTED_PLATFORMS` can be remove altogether from the target because the project settings already list all three platforms as the default.

Obviously, this change need to be made to both the `Debug` and the `Release` config.

**Comment by khatchik** [comment]
Can we get this done? It is a line of code and will unblock anybody trying to use Macaw for Catalyst Apps...

**Comment by ystrot** [comment]
Hi @khatchik,

Is this a fix you're waiting for: https://github.com/exyte/Macaw/pull/614 ? It was already merged to the master and will be part of the next release.

**Comment by simonboots** [comment]
Hi @ystrot,

I just tried to build Macaw as a Catalyst binary and noticed that `SUPPORTED_PLATFORMS` lists `macOS` as a platform (as of #614). However, `macOS` doesn't seem to be a valid platform. The correct platform name for macOS is `macosx`.

**Comment by ystrot** [comment]
Hi @simonboots,

Could you please create a corresponding PR? In this case I'll be able to merge it today.
