### ISSUE TITLE
ContentMode not working for some SVGs

### ISSUE THREAD

**Issue by GDGapps** [exyte/Macaw#657]
Hello,

ContentMode does not work for some svg, for example "worldLow". Regardless of what I choose, it is always shown as very small in the center-left.

I have attached one svg in which it does not work for reference.
Thanks
[worldLow.svg.zip](https://github.com/exyte/Macaw/files/3994185/worldLow.svg.zip)

**Comment by GDGapps** [comment]
I noticed the issue is solved if I remove the dimension and viewbox attributes from the SVG

**Comment by f3dm76** [comment]
Hello @GDGapps, this happens cause the extra "blank" space is included into this svg's viewBox. You can easily check this by setting a background color for the root <svg> item:
<img width="1051" alt="Screenshot 2020-06-03 at 16 20 54" src="https://user-images.githubusercontent.com/9447630/83619539-3466ba80-a5b6-11ea-82e9-8562b5bfd84b.png">

We do not modify viewBoxes, since it is a part of the scene. Indeed if you were to remove the viewBox entirely, it would work as you expect it.

**Comment by icearith** [comment]
any progress on this "contentMode" issue?
